# Site settings
title: Mr Christopher Bradish
email: chris@bradi.sh
url: https://chris.bradi.sh
description: "Paediatric Orthopaedic expert in Medicolegal cases specialisin in children with limb deformities, arthrogryposis, neurofibromatosis, brachial plexus palsies and osteogenesis imperfecta."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF #18bc9c
  secondary: FD6E8A #2c3e50 
  secondary-dark: A2122F #233140

# Footer settings
footer:
  copyright: Christopher Bradish
  location: location


# Build settings
markdown: kramdown
permalink: pretty
