# Site settings
title: Mr Christopher Bradish
email: website@bradi.sh
url: http://paediatricortopaedic.com
description: "Paediatric Orthopaedic expert in Medicolegal cases specialisin in children with limb deformities, arthrogryposis, neurofibromatosis, brachial plexus palsies and osteogenesis imperfecta."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c
  secondary: 2c3e50 
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Christopher Bradish
  location: location


# Build settings
markdown: kramdown
permalink: pretty
